[project]
name = "tg-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4==4.14.3",
    "python-dotenv>=1.2.1",
    "python-telegram-bot>=22.5",
    "python-telegram-bot[job-queue]",
    "requests>=2.32.5",
]
